"""Signal 1 — LLM holistic read via Groq (llama-3.3-70b-versatile).

Asks the model for a single AI-likelihood plus one-line reasoning, in strict
JSON. This captures semantic/stylistic coherence — the holistic "does this read
as a human voice or as AI" judgment that no single statistic can.

Degrades gracefully: on a missing key, API error, or unparseable response it
returns ai_likelihood=None so scoring can drop it and fall back to the two
heuristic signals rather than crashing the request.
"""
from __future__ import annotations

import json
import re

from config import GROQ_API_KEY, LLM_MODEL

_PROMPT = """You are a forensic text analyst. Assess whether the text below was \
written by a human or generated by an AI language model.

Judge holistically: genuine human voice, specific lived detail, and natural \
irregularity point to HUMAN; generic phrasing, even hedged tone, and formulaic \
structure point to AI. Be cautious about accusing formal or non-native-English \
human writing of being AI.

Respond with ONLY a JSON object, no other text:
{{"ai_likelihood": <float 0.0-1.0>, "reasoning": "<one short sentence>"}}
where 0.0 = certainly human, 1.0 = certainly AI.

TEXT:
\"\"\"
{text}
\"\"\""""


def _extract_json(raw: str) -> dict | None:
    match = re.search(r"\{.*\}", raw, re.DOTALL)
    if not match:
        return None
    try:
        return json.loads(match.group(0))
    except json.JSONDecodeError:
        return None


def llm_signal(text: str) -> dict:
    """Return {ai_likelihood: float|None, detail: {...}}.

    ai_likelihood is None when the signal is unavailable (no key / error /
    bad parse) so the caller knows to drop it from scoring.
    """
    if not GROQ_API_KEY:
        return {"ai_likelihood": None, "detail": {"error": "no GROQ_API_KEY set"}}

    try:
        from groq import Groq  # imported lazily so the app starts without the key

        client = Groq(api_key=GROQ_API_KEY)
        resp = client.chat.completions.create(
            model=LLM_MODEL,
            messages=[{"role": "user", "content": _PROMPT.format(text=text)}],
            temperature=0.0,  # deterministic as possible for repeatability
            max_tokens=200,
        )
        raw = resp.choices[0].message.content
    except Exception as exc:  # network/auth/rate-limit -> degrade, don't crash
        return {"ai_likelihood": None, "detail": {"error": str(exc)[:200]}}

    parsed = _extract_json(raw or "")
    if not parsed or "ai_likelihood" not in parsed:
        return {"ai_likelihood": None, "detail": {"error": "unparseable", "raw": (raw or "")[:200]}}

    try:
        score = max(0.0, min(1.0, float(parsed["ai_likelihood"])))
    except (TypeError, ValueError):
        return {"ai_likelihood": None, "detail": {"error": "non-numeric score"}}

    return {
        "ai_likelihood": round(score, 4),
        "detail": {"reasoning": str(parsed.get("reasoning", ""))[:300]},
    }


if __name__ == "__main__":
    print(llm_signal("The mitochondria is the powerhouse of the cell."))
